let formattedText;

if(status === "step1"){
    formattedText = "in attesa di creazione"
}else if(status === "step2"){
    formattedText = "da controllare"
}else if(status === "step3"){
    formattedText = "controllata"
}else if(status === "step4"){
    formattedText = "inviata al cliente"
}else if(status === "step5"){
    formattedText = "tornata con firma"
}else{
    formattedText = status
}
return formattedText;